# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 999432cd1450b6b78393a389681bf1f0224fed6d7103d16e73c82ee3d54dfc2460ede1f254012ef0c2e766cf28bb24e0f8dfade1820be177942d0c2379d0b485

test:
  secret_key_base: ed8ebbaca2651cfb7cd70e820b9f0fde2914d1e3ce94161aa33c0d327d2ff10b09e26fbd90bca75cf73828e6bc522aaf28a35a8a0f0b9144a52b6d3934ada311

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
